spring:
  application:
    name: server-api
  profiles:
    default: mysql
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:321821547881-tmg0rk0c715ag4v5ed3pqirnabhg02it.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET: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}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub

server:
  port: ${SERVER_PORT:8080}

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:file:./data/smart_campus_db;MODE=MySQL;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: never

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3036/smart_campus_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql